name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

env: 
  VCS_WORKSPACE_NAME: "github-workflow"
  TF_VERSION: "0.14.3"
  WORKING_DIRECTORY: ""
  VCS_REPO: "mayankagarwal19911/test-workflow"
  VCS_BRANCH: "main"
  TFE_ADDR: "https://app.terraform.io"
  TFE_ORG: "test-cicd"

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development 

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
  
    steps:

    - name: update apt
      run: sudo apt update && sudo apt upgrade
      
    - name: install curl
      run: sudo apt install curl

    # Checkout the repository to the GitHub Actions runner
    - name: create namespace
      run: |
          curl -X POST -H "Accept:application/vnd.github+json" -H "Authorization:Bearer ${{ secrets.TFE_ORG_TOKEN }}" -H "Content-Type:application/vnd.api+json" --data @payload-2.json ${TFE_ADDR}/api/v2/organizations/${TFE_ORG}/workspaces
    
